export const POKEMON_LIST_REQUEST = "POKEMON_LIST_REQUEST";
export const POKEMON_LIST_SUCCESS = "POKEMON_LIST_SUCCESS";
export const POKEMON_LIST_FAILURE = "POKEMON_LIST_FAILURE";

export const POKEMON_OBJECT_REQUEST = "POKEMON_OBJECT_REQUEST";
export const POKEMON_OBJECT_SUCCESS = "POKEMON_OBJECT_SUCCESS";
export const POKEMON_OBJECT_FAILURE = "POKEMON_OBJECT_FAILURE";
