export const POKEMON_LIST_REQUEST = "POKEMON_LIST_REQUEST";
export const POKEMON_LIST_SUCCESS = "POKEMON_LIST_SUCCESS";
export const POKEMON_LIST_FAILURE = "POKEMON_LIST_FAILURE";

export const POKEMON_OBJECT_REQUEST = "POKEMON_OBJECT_REQUEST";
export const POKEMON_OBJECT_SUCCESS = "POKEMON_OBJECT_SUCCESS";
export const POKEMON_OBJECT_FAILURE = "POKEMON_OBJECT_FAILURE";

export const POKEMON_SPECIES_REQUEST = "POKEMON_SPECIES_REQUEST";
export const POKEMON_SPECIES_SUCCESS = "POKEMON_SPECIES_SUCCESS";
export const POKEMON_SPECIES_FAILURE = "POKEMON_SPECIES_FAILURE";

export const EVOLUTION_CHAIN_REQUEST = "EVOLUTION_CHAIN_REQUEST";
export const EVOLUTION_CHAIN_SUCCESS = "EVOLUTION_CHAIN_SUCCESS";
export const EVOLUTION_CHAIN_FAILURE = "EVOLUTION_CHAIN_FAILURE";

export const UPDATE_SEARCH = "UPDATE_SEARCH";